### PR TITLE
Resolves: 100099 - Fix organization month credit calculation

### PR DESCRIPTION
**Pull request by marwand**
In Organization.xml & TransactionHistory.xml, used check#PartyActivation to calculate used credits. 

@acetousk , I  used one of [activeOrgId or the first entry in userOrgIds] to call check#PartyActivation. Looking at the logic in check#PartyActivation, it shouldn't matter because it looks at all orgs with the same ownerPartyId, but wanted to run it by you first.

Let me know if I missed anything.

### CODE REVIEW

**Comment by acetousk** [comment]
@marwand In the settings app there is no guarantee of activeOrgId. The whole point of the app is to pick an organization for activeOrgId. 

How the data model works is that an the currently logged in user can own many organizations by the Party.ownerPartyId. 

The check#PartyActivation service calculates the total for each organization the user owns based on any organizationPartyId the user owns.

**Comment by marwand** [comment]
@acetousk The way I would do this is to reconsider passing organizationPartyId to check#PartyActivation. What currently happens, like you said, is you pass in an organizationPartyId, if finds it to get ownerPartyId and then uses that to find all orgs owned by that party and perform the calculations on them. What I suggest is to omit it completely and get the user's party id from the execution context.

activateOrDeactivate#Organization is the only reference (other than TransactionHistory, Organization screens) to the service, and its behavior would not be affected by that change. 

Here's what it'll look like:
```
<service verb="check" noun="PartyActivation" authenticate="anonymous-all">
    <in-parameters>
        <parameter name="finAccountTypeId" required="true" default-value="OrganizationMonthCredit"/>
        <parameter name="currentTimestamp" default="ec.user.nowTimestamp" type="Timestamp" required="true"/>
    </in-parameters>
    <out-parameters>
        <parameter name="organizationChangeList" type="List"/>
        <parameter name="needsCredits" type="Boolean"/>
        <parameter name="creditsNeeded" type="Integer"/>
        <parameter name="totalCreditsUsed" type="BigDecimal"/>
        <parameter name="periodFromDate" type="Timestamp"/>
        <parameter name="periodThruDate" type="Timestamp"/>
        <parameter name="activationThruDate" type="Timestamp"/>
    </out-parameters>
    <actions>
        <set field="activationThruDate" from="new Timestamp(ZonedDateTime.ofInstant(Instant.ofEpochMilli(
            (long) currentTimestamp.time), ZoneId.systemDefault()).plusDays(1).toInstant().toEpochMilli())"/>
        <set field="periodFromDate" from="new Timestamp(ZonedDateTime.ofInstant(Instant.ofEpochMilli(
            (long) currentTimestamp.time), ZoneId.systemDefault()).withDayOfMonth(1).toInstant().toEpochMilli())"/>
        <set field="periodThruDate" from="new Timestamp(ZonedDateTime.ofInstant(Instant.ofEpochMilli(
            (long) currentTimestamp.time), ZoneId.systemDefault()).plusMonths(1).withDayOfMonth(1).toInstant().toEpochMilli())"/>

        <set field="userPartyId" from="ec.user.userAccount?.partyId"/>
        <if condition="!userPartyId"><return type="warning" message="No party was found for active user"/></if>
        <entity-find entity-name="mantle.account.financial.FinancialAccount" list="financialAccountList" distinct="true">
            <econdition field-name="ownerPartyId" from="userPartyId"/>
            <econdition field-name="finAccountTypeId"/>
            <econdition field-name="statusId" value="FaActive"/>
            <date-filter valid-date="currentTimestamp"/>
            <select-field field-name="ownerPartyId,finAccountId,availableBalance"/>
        </entity-find>
<!--            <log level="warn" message="check#PartyActivation financialAccountList ${financialAccountList}"/>-->
        <if condition="financialAccountList.size() == 0">
            <set field="needsCredits" from="true"/>
            <set field="creditsNeeded" from="1" type="Integer"/>
            <return/>
        </if>

        <!-- if there are multiple financial accounts for an organization, then remove all but the one with the most credits -->
        <set field="financialAccount" from="financialAccountList.groupBy{it.ownerPartyId}.collect{it.value.max{it.availableBalance}}[0]"/>

        <set field="organizationChangeList" from="[]"/>
        <set field="totalCreditsUsed" from="0.0" type="BigDecimal"/>
        <entity-find entity-name="mantle.party.Party" list="organizationList">
            <econdition field-name="partyTypeEnumId" value="PtyOrganization"/>
            <econdition field-name="disabled" value="N" or-null="true"/>
            <econdition field-name="ownerPartyId" from="userPartyId"/>
        </entity-find>
        <if condition="organizationList.size() == 0">
            <set field="needsCredits" from="true"/>
            <set field="creditsNeeded" from="1" type="Integer"/>
            <return/>
        </if>
        <iterate list="organizationList" entry="organization">
            <service-call name="coarchy.CoarchyServices.calculate#PartyActivationUsage" in-map="[
                organizationPartyId:organization.partyId, periodFromDate:periodFromDate, periodThruDate:periodThruDate,
                activationThruDate:activationThruDate]" out-map="context"/>

            <set field="organizationChangeList" from="organizationChangeList + [organizationId:organization.partyId,activationPeriodCount:activationPeriodCount]"/>
            <!--                    <log level="warn" message="check#PartyActivation organization ${organization} activationPeriodCount ${activationPeriodCount}"/>-->
            <set field="totalCreditsUsed" from="totalCreditsUsed + activationPeriodCount" type="BigDecimal"/>
        </iterate>

<!--            <entity-find-count entity-name="mantle.party.PartyActivationAndParty" count-field="activatedOrganizationCount">-->
<!--                <econdition field-name="ownerPartyId" from="organization.ownerPartyId"/>-->
<!--                <date-filter/></entity-find-count>-->
<!--            <log level="warn" message="check#PartyActivation activatedOrganizationCount ${activatedOrganizationCount} totalCreditsUsed ${totalCreditsUsed} financialAccount.availableBalance ${financialAccount.availableBalance}"/>-->
        <set field="creditsNeeded" from="0.0" type="BigDecimal"/>
        <set field="needsCredits" from="false"/>
        <if condition="totalCreditsUsed &gt;= financialAccount.availableBalance">
            <set field="needsCredits" from="true"/>

            <set field="creditsNeededMax" from="(totalCreditsUsed-financialAccount.availableBalance).setScale(0, BigDecimal.ROUND_UP)" type="Integer"/>
            <set field="creditsNeeded" from="creditsNeededMax&gt;1.0?creditsNeededMax:1"/>
        </if>

<!--            <log level="warn" message="check#PartyActivation context.toString() ${context.toString()}"/>-->
    </actions>
</service>
```
and in the screens, simply call it like this:
```
        <service-call name="coarchy.CoarchyServices.check#PartyActivation" 
            in-map="[finAccountTypeId:'OrganizationMonthCredit']" 
            out-map="partyActivationOut" />
        <set field="totalCreditsUsed" type="BigDecimal" from="partyActivationOut.totalCreditsUsed?:0.0" />
```

Let me know what you think

**Comment by acetousk** [comment]
@marwand Instead of assuming userPartyId is the currently logged in user, pass in the party to make it more flexible and like check#PartyActivationDaily

**Comment by acetousk** [comment]
This looks good

**Review by acetousk — APPROVED** [review]

**Comment by acetousk** [comment]
I'm still seeing:
image

Would it be easier to just put the No Activities in a ol element?

**Comment by marwand** [comment]
@acetousk We could, but it'll be numbered. Another solution would be to add a line break before and after. Check #19. 
Sorry this keeps on being reopened, we should probably setup some test data that span across all the cases in the outline view, to ease future testing.

**Comment by acetousk** [comment]
@marwand Feel free to add test data to make our lives easier

**Pull request merged**
