### PR TITLE
Resolves CoarchyP-100022: Owner of an organization can invite a user to join multiple times

### PR DESCRIPTION
**Pull request by marwand**
Task description
```
For testing email:
Run docker run -p 1080:1080 -p 1025:1025 maildev/maildev.
Go to http://localhost:1080 in the browser

See EditOrganization screen Invite User.
Type in an email and see the email sent.
Type in the same email and see that an additional email is sent.

There should be a warning for inviting a user who is already part of the organization, and no email sent
```

Changelog:
- In invite#User service, added a check to prevent sending an invitation email to already invited users within an organization

### CODE REVIEW

**Comment by marwand** [comment]
@acetousk, I also want to clear up the definition of 'already part of the organization'. As it currently stands, If my organization 'Organization X' has invited user 'user1@gmail.com' and the user has not yet set up his account, the user is considered 'part of the organization', and therefore the invitation will not be resent.

I believe we should consider the case where the user wants his invitation to be resent due to email bouncing or other delivery issues. If that's the case then I suggest that we distinguish between an **invited user** and an **activated user**. What do you think?

**Comment by acetousk** [comment]
> @acetousk, I also want to clear up the definition of 'already part of the organization'. As it currently stands, If my organization 'Organization X' has invited user '[user1@gmail.com](mailto:user1@gmail.com)' and the user has not yet set up his account, the user is considered 'part of the organization', and therefore the invitation will not be resent.
> 
> I believe we should consider the case where the user wants his invitation to be resent due to email bouncing or other delivery issues. If that's the case then I suggest that we distinguish between an **invited user** and an **activated user**. What do you think?

@marwand We should consider that. I am currently working on sending emails when the user has been invited, but hasn't accepted or opened the email.

Let's not worry about bouncing or delivery issues for now. Unless you think it'll be a major problem

Thanks for your thoughts

**Review by acetousk — APPROVED** [review]
Looks good so far

**Comment by marwand** [comment]
> > @acetousk, I also want to clear up the definition of 'already part of the organization'. As it currently stands, If my organization 'Organization X' has invited user '[user1@gmail.com](mailto:user1@gmail.com)' and the user has not yet set up his account, the user is considered 'part of the organization', and therefore the invitation will not be resent.
> > I believe we should consider the case where the user wants his invitation to be resent due to email bouncing or other delivery issues. If that's the case then I suggest that we distinguish between an **invited user** and an **activated user**. What do you think?
> 
> @marwand We should consider that. I am currently working on sending emails when the user has been invited, but hasn't accepted or opened the email.
> 
> Let's not worry about bouncing or delivery issues for now. Unless you think it'll be a major problem
> 
> Thanks for your thoughts

Don't think its a major problem, but should be backlogged for the future.

**Comment by acetousk** [comment]
Added to backlog.

**Pull request merged**
