### PR TITLE
New Feature: Request For Proposal

### PR DESCRIPTION
**Pull request by marwand**
Related tasks:
- 100134 Request for proposal
- CoarchyP-100122 Update Product Evaluation Statements UX
- CoarchyP-100121 Implement Copy on Write for Activities, Statements & related
- CoarchyP-100125 Vendor App Changes
- CoarchyP-100123 Product Evaluation UI & Behavior Changes
- CoarchyP-100127 Ensure organization-based security on ProductEvaluation entities

Changes:
- Added ProductEvaluation entities
- Updated ValueStatements/Activities & related entities to support Copy on Write
- Updated logic in Coarchy app/services to support Copy on write on Acitivites/Statements
- Added ProductEvaluation screens & services
- Added Vendor app
- Added vendor-oriented organization filter services (similar to get#PartyOrganizationInfo & setup#UserOrganizationInfo), added custom org picker to avoid cross-organization leaks
- Added vendor user group & filter sets

### CODE REVIEW

**Review by acetousk — COMMENTED** [review]
There seems to be a lot of duplicate code, and a lot of code. Is all of that code really needed?

Is there ways to reduce the amount of code that is being reused by following the patterns in SimpleScreens and how those screens are used in multiple apps like MarbleERP and HiveMind?

**Comment by marwand** [comment]
> There seems to be a lot of duplicate code, and a lot of code. Is all of that code really needed?
> 
> Is there ways to reduce the amount of code that is being reused by following the patterns in SimpleScreens and how those screens are used in multiple apps like MarbleERP and HiveMind?

Thanks for the feedback - good point. I merged the EditProductEval screens & kept the version in cointernal. I'm also going to do a quick code review & remove anything thats unused at this point.

**Comment by acetousk** [comment]
> > There seems to be a lot of duplicate code, and a lot of code. Is all of that code really needed?
> > Is there ways to reduce the amount of code that is being reused by following the patterns in SimpleScreens and how those screens are used in multiple apps like MarbleERP and HiveMind?
> 
> Thanks for the feedback - good point. I merged the EditProductEval screens & kept the version in cointernal. I'm also going to do a quick code review & remove anything thats unused at this point.

Alright let me know when you're done with that code review.

**Comment by marwand** [comment]
> > > There seems to be a lot of duplicate code, and a lot of code. Is all of that code really needed?
> > > Is there ways to reduce the amount of code that is being reused by following the patterns in SimpleScreens and how those screens are used in multiple apps like MarbleERP and HiveMind?
> > 
> > 
> > Thanks for the feedback - good point. I merged the EditProductEval screens & kept the version in cointernal. I'm also going to do a quick code review & remove anything thats unused at this point.
> 
> Alright let me know when you're done with that code review.

It's good to go :+1:

**Pull request merged**
